GET http://localhost:3000/recipes/25.json

###
GET http://localhost:3000/recipes.json?q=bread&tags=dinner,indian



###
GET http://localhost:3000/recipes.json?tags=1,71


###
GET http://localhost:3000/tags.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Evan",
  "email": "evan@email.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "evan@email.com",
  "password": "password"
}