GET http://localhost:3000/recipes/752.json
Authorization: Bearer

###
GET http://localhost:3000/recipes.json?q=bread&tags=dinner,indian



###
GET http://localhost:3000/recipes.json


###
GET http://localhost:3000/tags.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Evan",
  "email": "evan@email.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "evan@email.com",
  "password": "password"
}

### Favorite Recipes Create
POST http://localhost:3000/favorite_recipes.json
Authorization: Bearer 
Content-Type: application/json

{
  "recipe_id": 812
}

### Favorite Recipes Index
GET http://localhost:3000/favorite_recipes.json
Authorization: Bearer 

### Favorite Recipes Update
PATCH http://localhost:3000/favorite_recipes/2.json
Authorization: Bearer 
Content-Type: application/json

{
  "has_made": false
}

### Favorite Recipes Destroy
DELETE http://localhost:3000/favorite_recipes/2.json
Authorization: Bearer 

### Favorite Recipes 'show'
GET http://localhost:3000/favorite_recipes/751.json
Authorization: Bearer 

### Fav Searches Index
GET http://localhost:3000/favorite_searches.json
Authorization: Bearer

### Fav Searches Create
POST http://localhost:3000/favorite_searches.json
Authorization: Bearer
Content-type: application/json

{
  "q": "burrito",
  "tags": "mexican,dinner"
}

###
GET http://localhost:3000/recipe_ingredients/712.json


###
GET http://localhost:3000/ingredients/12.json