GET http://localhost:3000/recipes/25.json

###
GET http://localhost:3000/recipes.json?q=chocolate&i=banana&tags=dinner



###
GET http://localhost:3000/recipes.json?tags=1,71


###
GET http://localhost:3000/tags.json